- constants/index.ts
---
- https://app.asana.com/0/0/1206198147057618
> :recycle: refactor: replace explorer link

- context/modal/index.tsx
- hooks/use-Modal/index.ts
- views/swap/swap-button.tsx
---
- https://app.asana.com/0/0/1206628060736091
> :sparkles: Add preview button

- components/hoc/index.ts
- components/hoc/with-object-id-guard.tsx
- components/hoc/with-params-guard.tsx
- constants/pools.ts
- constants/routes.ts
- interface/index.ts
- pages/pools/details.tsx
- views/components/pool-title-bar/index.tsx
- views/components/pool-title-bar/pool-title-bar.types.ts
- views/pool-details/index.tsx
- views/pool-details/pool-details.types.ts
- views/pools/pool-card/index.tsx
- views/pools/pool-card/pool-card-header.tsx
- views/pools/pool-card/pool-card-info.tsx
- views/pools/pool-card/pool-card.types.ts
---
- https://app.asana.com/0/0/1206685046725483
> :sparkles: Pool Details Header

- components/svg/search.tsx
- views/pools/header/action-group.tsx
- views/pools/header/index.tsx
- views/pools/header/search-mobile.tsx
- views/pools/index.tsx
---
- https://app.asana.com/0/0/1206685046825512
> :sparkles: feat: pool header

- views/pool-details/index.tsx
- views/pool-details/pool-details-tabs/index.tsx
- views/pool-details/pool-details-tabs/pool-details-tabs-item.tsx
- views/pool-details/pool-details-tabs/pool-details-tabs.types.ts
- views/pool-details/pool-details.types.ts
---
- https://app.asana.com/0/0/1206703665848193
> :sparkles: feat: detail tabs

- pages/pools/details.tsx
- views/pool-details/pool-form/component/field/field.types.ts
- views/pool-details/pool-form/component/field/index.tsx
- views/pool-details/pool-form/component/receive-section/index.tsx
- views/pool-details/pool-form/component/receive-section/receive-section.types.ts
- views/pool-details/pool-form/deposit.tsx
- views/pool-details/pool-form/index.tsx
- views/pools/pools.types.ts
---
- https://app.asana.com/0/0/1206703665848177
> :sparkles: Pool details form deposit

- pages/pools/create.tsx
- views/pool-create/index.tsx
- views/pool-create/pool-create-steps/index.tsx
- views/pool-create/pool-create.types.ts
- views/pool-create/select-volatility/index.tsx
- views/pool-create/select-volatility/select-stable-card/illustration.tsx
- views/pool-create/select-volatility/select-stable-card/index.tsx
- views/pool-create/select-volatility/select-volatibility-card.tsx
- views/pool-create/select-volatility/select-volatibility.types.ts
- views/pool-create/select-volatility/select-volatile-card/illustration.tsx
- views/pool-create/select-volatility/select-volatile-card/index.tsx
---
- https://app.asana.com/0/0/1206720077088233
> ✨ Add Algorithm cards

- views/pool-create/pool-create-steps/index.tsx
---
- https://app.asana.com/0/0/1206780498101196
> 🐛  Fix step counter

- components/token-icon/token-icon.types.ts
- pages/pools/create.tsx
- views/pool-create/index.tsx
- views/pool-create/pool-create-button.tsx
- views/pool-create/pool-create-steps/index.tsx
- views/pool-create/pool-create.types.ts
- views/pool-create/select-coins/index.tsx
- views/pool-create/select-coins/input/header-info.tsx
- views/pool-create/select-coins/input/index.tsx
- views/pool-create/select-coins/input/input.types.ts
- views/pool-create/select-coins/input/select-token.tsx
- views/pool-create/select-volatility/index.tsx
---
- https://app.asana.com/0/0/1206720079328163
> ✨  select token and deposit section

- views/pool-create/pool-create-button.tsx
- views/pool-create/pool-create.data.tsx
- views/pool-create/pool-create.types.ts
- views/pool-create/select-dex/index.tsx
- views/pool-create/select-dex/select-dex.data.ts
- views/pools/pool-card/pool-card.data.ts
---
- https://app.asana.com/0/0/1206720079328167
> ✨ add select dex

- views/pool-create/index.tsx
- views/pool-create/pool-create-steps/index.tsx
- views/pool-create/pool-create-steps/pool-create-steps.types.ts
---
- https://app.asana.com/0/0/1206800876793593
> :bug: Step remove click event

- views/pool-create/select-dex/index.tsx
---
- https://app.asana.com/0/0/1206800876793600
> :bug: Zindex in Dex List

- constants/fees.tsx
- hooks/use-get-all-coins/index.ts
- views/swap/input/select-token.tsx
- views/swap/swap-button.tsx
- views/swap/swap-preview-modal/index.tsx
- views/swap/swap-preview-modal/swap-preview-modal-summary.tsx
- views/swap/swap.types.ts
---
- https://app.asana.com/0/0/1206628060736095
> ✨  Swap preview modal

- pages/pools/create.tsx
- views/pool-create/select-coins/input/select-token.tsx
---
- https://app.asana.com/0/0/1206800877066572
> :bug: remove duplicate token selected

- views/pool-create/pool-create.data.tsx
- views/pool-create/select-type/index.tsx
- views/pool-create/select-type/select-type-amm/illustration.tsx
- views/pool-create/select-type/select-type-amm/index.tsx
- views/pool-create/select-type/select-type-card.tsx
- views/pool-create/select-type/select-type-clamm/illustration.tsx
- views/pool-create/select-type/select-type-clamm/index.tsx
- views/pool-create/select-type/select-volatibility.types.ts
---
- https://app.asana.com/0/0/1206720077088227
> ✨  Add type section

- views/pool-create/index.tsx
- views/pool-create/pool-summary/index.tsx
---
- https://app.asana.com/0/0/1206720276890018
> ✨  add dialog to create pool

- views/pool-details/additional-info/components/accordion/item-token.tsx
---
- https://app.asana.com/0/0/1206801133596176
> :bug: Fix pool composition tag margin

- views/airdrop/airdrop-button.tsx
- views/airdrop/airdrop-choose-coin.tsx
- views/airdrop/airdrop-progress-indicator.tsx
- views/airdrop/airdrop-select-token.tsx
- views/airdrop/airdrop-summary.tsx
- views/airdrop/airdrop-upload-file-card.tsx
- views/airdrop/airdrop-upload-file.tsx
- views/airdrop/airdrop-upload-status-card.tsx
- views/airdrop/airdrop-upload-status.tsx
- views/airdrop/index.tsx
---
- https://app.asana.com/0/0/1206801133596198
> :bug: Fix airdrop text color

- views/faucet/index.tsx
- views/faucet/mint-balances.tsx
- views/faucet/mint-form.tsx
---
- https://app.asana.com/0/0/1206801133596210
> 🐛  Fix faucet text color

- constants/coins.ts
- constants/index.ts
- constants/packages.ts
- views/swap/index.tsx
- views/swap/input/select-token.tsx
- views/swap/swap-button.tsx
- views/swap/swap-manager/index.tsx
- views/swap/swap-manager/swap-manager-field.tsx
- views/swap/swap-manager/swap-manager.utils.ts
- views/swap/swap-manager/swap-messages.tsx
- views/swap/swap-manager/swap-path.tsx
- views/swap/swap-preview-button.tsx
- views/swap/swap-preview-modal/index.tsx
- views/swap/swap.types.ts
---
- https://app.asana.com/0/0/1206780500103827
> 🐛 Fix Swap flow

- views/pool-create/select-dex/index.tsx
---
- https://app.asana.com/0/0/1206801133596164
> :bug: Fix select token dropdown alignment

- views/create-token/create-token-form/index.tsx
- views/create-token/hero/title.tsx
---
- https://app.asana.com/0/0/1206801133280607
> :recycle: Refactor text color

- views/pool-details/additional-info/index.tsx
---
- https://app.asana.com/0/0/1206801133596184
> :bug: fix: responsiviness

- components/account-info/menu-options/option-item.tsx
- components/account-info/movement-network.tsx
---
- https://app.asana.com/0/0/1206801469137428
> :bug: fix: disable testnet

- views/pools/header/action-group.tsx
---
- https://app.asana.com/0/0/1206801133596158
> :bug: fix: mobile add pool button

- views/pool-details/pool-form/index.tsx
- views/pools/header/action-group.tsx
---
- https://app.asana.com/0/0/1206801133596190
> :bug: fix: pool form responsiviness

- components/svg/index.ts
- components/svg/wallet.tsx
- views/airdrop/airdrop-body.tsx
- views/airdrop/airdrop-choose-method.tsx
- views/airdrop/airdrop-form.data.ts
- views/airdrop/airdrop.types.ts
- views/airdrop/index.tsx
---
- https://app.asana.com/0/0/1206806201944378
> :sparkles: Airdrop Method

- views/airdrop/airdrop-preview-modal.tsx
- views/airdrop/airdrop-summary.tsx
---
- https://app.asana.com/0/0/1206806201944386
> :lipstick: Checking ui fixes

- components/svg/check.tsx
- components/svg/warning.tsx
- hooks/use-dialog/index.tsx
- views/airdrop/airdrop-progress-indicator.tsx
- views/airdrop/index.tsx
- views/pool-create/pool-summary/index.tsx
- views/pool-details/pool-form/deposit.tsx
- views/pool-details/pool-form/withdraw/index.tsx
---
- https://app.asana.com/0/0/1206806202223903
- https://app.asana.com/0/0/1206806202223907
- https://app.asana.com/0/0/1206806202223895
> :recycle: Airdrop progress indicator

- views/airdrop/airdrop-upload-status.tsx
---
- https://app.asana.com/0/0/1206806202223899
> :sparkles: feat: progress summary accordion

- components/account-info/movement-network.tsx
- constants/wrapper-variants.ts
---
- https://app.asana.com/0/0/1206939424225244
> :sparkles: Add animation to profile and switch account

- views/airdrop/airdrop-choose-coin.tsx
- views/airdrop/airdrop-choose-method.tsx
- views/airdrop/airdrop-input.tsx
- views/airdrop/airdrop-preview-modal.tsx
- views/components/pool-title-bar/index.tsx
- views/create-token/create-token-form/index.tsx
- views/faucet/mint-balances.tsx
- views/faucet/mint-form.tsx
- views/pool-details/additional-info/index.tsx
- views/pool-details/pool-form/component/field/index.tsx
- views/pool-details/pool-form/component/receive-section/index.tsx
- views/pool-details/pool-form/deposit.tsx
- views/pool-details/pool-form/index.tsx
- views/pool-details/pool-form/preview/wrapper/index.tsx
- views/pool-details/pool-form/withdraw/index.tsx
- views/pool-details/pool-form/withdraw/selection.tsx
- views/swap/index.tsx
- views/swap/manage-slippage/index.tsx
---
- https://app.asana.com/0/0/1206969712958371
> :lipstick: Same bg in all page

- views/pools/find-pool-modal/find-pool-dialog/index.tsx
---
- https://app.asana.com/0/0/1206859474951532
> :bug: Refactor pool doesn't exist UI

- views/pools/pool-card-list.tsx
- views/pools/pools.types.ts
---
- https://app.asana.com/0/0/1206978601516296
> :bug: fix: wrong spelling

- views/swap/swap-preview-modal/index.tsx
---
- https://app.asana.com/0/0/1206978601516280
> :bug: fix: button icon

- constants/pools.ts
- views/pool-create/select-dex/select-dex.data.ts
- views/pools/pool-card/pool-card.data.ts
---
- https://app.asana.com/0/0/1206965392852523
> :fire: Remove sui-coins dex

- pages/index.tsx
- pages/pools/details.tsx
- views/swap/manage-slippage/manage-slippage-form/index.tsx
- views/swap/swap.types.ts
---
- https://app.asana.com/0/0/1206965392852541
> :fire: Remove deadline on slippage settings

- views/create-token/create-token-form/index.tsx
---
- https://app.asana.com/0/0/1206965392852546
> :lipstick: Change color to placeholder

- utils/string/index.ts
- views/swap/input/swap-manager-slider/index.tsx
---
- https://app.asana.com/0/0/1206978601516286
> :bug: fix: swap field decimals

- components/account-info/menu-options/menu-option.types.ts
- components/account-info/menu-options/option-item.tsx
- components/account-info/movement-network.tsx
- hooks/index.ts
- hooks/use-is-first-render/index.ts
---
- https://app.asana.com/0/0/1206965392852509
- https://app.asana.com/0/0/1206965392852517
> :bug: fix: menu

- views/pool-create/select-coins/index.tsx
- views/pool-create/select-coins/input/index.tsx
- views/pools/find-pool-modal/find-pool-modal.types.ts
- views/pools/find-pool-modal/select-coins/index.tsx
- views/pools/find-pool-modal/select-coins/select-token.tsx
---
- https://app.asana.com/0/0/1206965392852517
> :sparkles: feat: find pool dynamic fields

- views/pools/pool-card-list.tsx
- views/pools/pool-card/index.tsx
---
- https://app.asana.com/0/0/1206987214170496
> :bug: fix: pool card size

- constants/index.ts
- pages/index.tsx
- views/swap/input/dollar-value.tsx
- views/swap/input/index.tsx
- views/swap/input/select-token.tsx
- views/swap/input/swap-manager-slider/index.tsx
- views/swap/swap-button.tsx
- views/swap/swap-manager/swap-manager-field.tsx
- views/swap/swap-preview-modal/index.tsx
- views/swap/swap-preview-modal/swap-preview-modal-summary.tsx
- views/swap/swap.hooks.ts
- views/swap/swap.types.ts
---
- https://app.asana.com/0/0/1207014701462328
> :bug: Bug on preview modal and input swap

- views/pools/pool-card-list.tsx
---
- https://app.asana.com/0/0/1207030730251010
> :sparkles: feat: pool loading

- components/layout/sidebar/menu-item/menu-item-title.tsx
---
- https://app.asana.com/0/0/1207062875193139
> :bug: fix: side bar tooltip z-index

- views/pools/pool-filter/dropdown/index.tsx
---
- https://app.asana.com/0/0/1207353947321439
> 🐛 Fix dropdown click outside

- pages/index.tsx
- views/swap/index.tsx
- views/swap/input/balance.tsx
- views/swap/input/dollar-value.tsx
- views/swap/swap-flip-token.tsx
- views/swap/swap-header.tsx
- views/swap/swap-manager/swap-path.tsx
- views/swap/swap.data.ts
- views/swap/swap.types.ts
---
- https://app.asana.com/0/0/1207386110245270
> 🐛 Fix swap UI

- views/pool-create/pool-create.types.ts
- views/pool-create/pool-next-button.tsx
- views/pool-create/select-coins/index.tsx
- views/pool-create/select-coins/input/balance.tsx
- views/pool-create/select-coins/input/form-input-dollar.tsx
- views/pool-create/select-coins/input/header-info.tsx
- views/pool-create/select-coins/input/index.tsx
- views/pool-create/select-coins/input/input-max-button.tsx
- views/pool-create/select-coins/input/input.types.ts
- views/pool-create/select-coins/input/select-token.tsx
- views/pool-create/select-coins/input/token-field/index.tsx
- views/pool-create/select-coins/input/token-field/token-field.types.ts
---
- https://app.asana.com/0/0/1207460777880757
> :bug: Fix pool select token UI

- utils/coin/index.ts
- views/pool-create/index.tsx
- views/pool-create/pool-create.types.ts
- views/pool-create/pool-next-button.tsx
- views/pool-create/select-coins/index.tsx
- views/pool-create/select-coins/input/form-input-dollar.tsx
- views/pool-create/select-coins/select-coins-error-manager.tsx
- views/pool-create/select-coins/select-coins-error.tsx
---
- https://app.asana.com/0/0/1207460777817080
> :recycle: Refactor create pool error message

- pages/api/v1/metrics/weekly.ts
- server/lib/quest/index.ts
- server/model/metrics.ts
- views/analytics/analytics-card-list.tsx
- views/analytics/index.tsx
---
- https://app.asana.com/0/0/1208068380096446
> :sparkles: add weekly actions to metrics

- components/layout/footer/ social-link.data.ts
- components/layout/footer/index.tsx
- components/layout/footer/social-link.types.ts
---
- https://app.asana.com/0/0/1207920805551784
> :recycle: refactor: footer

- components/layout/footer/index.tsx
---
- https://app.asana.com/0/0/1207920805551784
> :recycle: refactor: footer new design

- views/swap/input/from-input.tsx
- views/swap/input/swap-manager-slider/index.tsx
- views/swap/swap.types.ts
---
- https://app.asana.com/0/0/1208084847965109
> :bug: Fix realtime optimization on swap slider

- views/swap/input/balance.tsx
---
- https://app.asana.com/0/0/1208187281947844
> :bug: fix: balance button update field

- views/swap/input/balance.tsx
- views/swap/input/swap-manager-slider/index.tsx
---
- https://app.asana.com/0/0/1208084847965109
> :bug: Fix slider real time update

- views/pools/header/index.tsx
- views/pools/pool-filter/dropdown/index.tsx
- views/pools/pool-filter/filter-selected-item/index.tsx
---
- https://app.asana.com/0/0/1208395299081552
> :sparkles: feat: pool search params
